# Powerlevel10k Theme: Gruvbox
# Retro warm colors on a dark background.

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  time
)

# Basic styling
typeset -g POWERLEVEL9K_BACKGROUND=235 # dark0_hard
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=142 # bright yellow
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=124 # bright red
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=142
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=124

# Segment Colors (Gruvbox Palette)
# dark1: 237, gray_245: 245, fg: 223
# red: 124, green: 106, yellow: 172, blue: 66, purple: 132, aqua: 72, orange: 166
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=223
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=66
typeset -g POWERLEVEL9K_DIR_FOREGROUND=72
typeset -g POWERLEVEL9K_VCS_FOREGROUND=106
typeset -g POWERLEVEL9K_STATUS_FOREGROUND=124
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=245
typeset -g POWERLEVEL9K_TIME_FOREGROUND=245
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=172
