# Powerlevel10k Theme: Matrix
# Green on black, digital rain style.

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  time
)

# Basic styling
typeset -g POWERLEVEL9K_BACKGROUND=0
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=40
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=40
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=196

# Segment Colors
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=40
typeset -g POWERLEVEL9K_DIR_FOREGROUND=46
typeset -g POWERLEVEL9K_VCS_FOREGROUND=34
typeset -g POWERLEVEL9K_STATUS_FOREGROUND=196
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=242
typeset -g POWERLEVEL9K_TIME_FOREGROUND=242
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=40
