# Powerlevel10k Theme: One Dark
# Based on Atom's One Dark theme.

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  time
)

# Basic styling
typeset -g POWERLEVEL9K_BACKGROUND=235
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=97
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=197
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_FOREGROUND=97
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_FOREGROUND=197

# Segment Colors (One Dark Palette)
# Black: 235, Red: 197, Green: 97, Yellow: 214, Blue: 75,
# Magenta: 199, Cyan: 80, White: 252, Bright Black: 240
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=252
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=75
typeset -g POWERLEVEL9K_DIR_FOREGROUND=80
typeset -g POWERLEVEL9K_VCS_FOREGROUND=97
typeset -g POWERLEVEL9K_STATUS_FOREGROUND=197
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=240
typeset -g POWERLEVEL9K_TIME_FOREGROUND=240
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=214
